version: '3.8'

name: dev-leptos-starter

services:
  site:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/app
    ports:
      - 3000:3000
      - 3001:3001
    command: ./site/dev.sh
